apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_dashboard: "1"
    {{- include "ata-otel-demo.labels" . | nindent 4 }}
  name: {{ include "ata-otel-demo.fullname" . }}-grafana-dashboards
data:
{{ (.Files.Glob "dashboards/*").AsConfig | indent 2 }}
