datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - access: proxy
      editable: true
      jsonData:
        maxLines: 1000
        timeout: "60"
      name: Logs
      type: loki
      uid: LOKIPROVISIONED
      url: http://loki-gateway
grafana.ini:
  alerting:
    enabled: false
  analytics:
    check_for_updates: false
  auth:
    disable_login_form: false
    disable_signout_menu: false
  auth.anonymous:
    enabled: true
    org_role: Admin
  grafana_net:
    url: https://grafana.net
  log:
    mode: console
    level: debug
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  plugins:
    enable_alpha: true
  unified_alerting:
    enabled: true
  users:
    editors_can_admin: true
    viewers_can_edit: true
## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  type: pvc
  enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 1Gi
plugins:
- camptocamp-prometheus-alertmanager-datasource
service:
  nodePort: 30300
  type: NodePort
sidecar:
  dashboards:
    SCProvider: true
    enabled: true
    folder: /tmp/dashboards
    label: grafana_dashboard
    labelValue: "1"
    provider:
      allowUiUpdates: true
      folder: Provisioned
      name: sidecarProvider
      orgid: 1
      type: file
      updateIntervalSeconds: 60
    resource: configmap
    watchMethod: WATCH
