# helm upgrade --install -f grafana-values.yaml --namespace default grafana grafana/grafana
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - access: proxy
      editable: true
      jsonData:
        implementation: prometheus
      name: Alertmanager
      type: alertmanager
      typeName: Alertmanager
      uid: AMGRPROVISIONED
      url: http://kps-alertmanager.default:9093
    - access: proxy
      editable: true
      jsonData:
        maxLines: 1000
        timeout: "60"
      name: Logs
      type: loki
      uid: LOKIPROVISIONED
      url: http://loki-gateway
    - access: proxy
      editable: true
      isDefault: false
      jsonData:
        alertmanagerUid: AMGRPROVISIONED
        cacheLevel: Medium
        prometheusType: Prometheus
      name: Prometheus
      type: prometheus
      uid: PMSPROVISIONED
      url: http://kps-prometheus.default:9090
      version: 1
    - access: proxy
      uid: TEMPOPROVISIONED
      name: Traces
      type: tempo
      typeName: Tempo
      url: 'http://tempo-query-frontend:3100'
      basicAuth: false
      isDefault: false
      jsonData:
        lokiSearch:
          datasourceUid: LOKIPROVISIONED
        nodeGraph:
          enabled: true
        tracesToLogs:
          datasourceUid: LOKIPROVISIONED
          filterByTraceID: true
          tags:
            - app
      editable: true
grafana.ini:
  alerting:
    enabled: false
  analytics:
    check_for_updates: false
  auth:
    disable_login_form: false
    disable_signout_menu: false
  auth.anonymous:
    enabled: true
    org_role: Admin
  grafana_net:
    url: https://grafana.net
  log:
    mode: console
    level: debug
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  plugins:
    enable_alpha: true
  unified_alerting:
    enabled: true
  users:
    editors_can_admin: true
    viewers_can_edit: true
## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  type: pvc
  enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 1Gi
plugins:
- camptocamp-prometheus-alertmanager-datasource
service:
  nodePort: 30300
  type: NodePort
sidecar:
  dashboards:
    SCProvider: true
    enabled: true
    folder: /tmp/dashboards
    label: grafana_dashboard
    labelValue: "1"
    provider:
      allowUiUpdates: true
      folder: Provisioned
      name: sidecarProvider
      orgid: 1
      type: file
      updateIntervalSeconds: 60
    resource: configmap
    watchMethod: WATCH
