alertmanager:
  enabled: true
  service:
    nodePort: 30903
    type: NodePort

fullnameOverride: kps

grafana:
  enabled: false

# Solve Error:
# failed to start container "node-exporter": Error response from daemon: path / is mounted on / but it is not a shared or slave mount
prometheus-node-exporter:
  hostRootFsMount:
    enabled: false

## Deploy a Prometheus instance
prometheus:
  enabled: true
  ## Settings affecting prometheusSpec
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec
  ##
  prometheusSpec:
    enableFeatures:
      - exemplar-storage
    retention: 7d
    scrapeInterval: "15s"
  service:
    nodePort: 30090
    type: NodePort
