fullnameOverride: kps
grafana:
  enabled: false

## Deploy a Prometheus instance
prometheus:
  enabled: true
  ## Settings affecting prometheusSpec
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec
  ##
  prometheusSpec:
    enableFeatures:
      - exemplar-storage
    retention: 7d
    scrapeInterval: "15s"
  service:
    nodePort: 30090
    type: NodePort

alertmanager:
  enabled: true
  service:
    nodePort: 30903
    type: NodePort
