apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_dashboard: "1"
    {{- include "boss.labels" . | nindent 4 }}
  name: {{ include "boss.fullname" . }}-grafana-dashboards
data:
{{ (.Files.Glob "dashboards/*").AsConfig | indent 2 }}
